### PR TITLE
WP 475 Lerna - publish all packages

### PR DESCRIPTION
**Pull request by mmcgahan**
**I'll test out the beta packages in mup-web before merging**

Here we go - from 1 npm package to 14. The diff is a bit inscrutable because of all the file moves and rearranging of code along with added Flow type information, but I suppose it could still use a scan from a few people in case there are any obvious blunders that stand out.

### What's changed?

- the `meetup-web-platform` package is deprecated
- the `meetup-web-platform` _repo_ now houses multiple npm packages
- each package has well-defined dependencies and Jest test config
- most code is now flow-typed
- Travis now uses lerna to publish packages

### What has _not_ changed

- unit tests still cover the same behavior
- no significant refactors, although some code was moved around in order to reduce circular dependencies (still more to do on that front, but it's slow going)
- meetup-web-components, meetup-web-mocks, mwp-cli, and all SDS repos are still independently maintained
- root-level config/testing:
   - eslint
   - babel
   - Makefile
   - flow type config
   - integration tests

### Followup:

- Documentation - 'How to contribute'/'How this repo works'
- Clean up/organize Flow types
- Clean up any remaining circular dependencies
- The MWP repos and their packages will be folded into this repo - SDS libs will probably move into a new monorepo

### CODE REVIEW

**Comment by mattkime** [comment]
Should this be pushing a git tag? Looks like the latest build on this PR is 1757 and I think I should see a corresponding 1757-beta tag on the repo.

**Comment by mmcgahan** [comment]
@mattkime `meetup-web-platform` is no longer published. I'll update the README badge in this branch to point to the latest version of the `mwp-core` package, which will be the same version used for all mwp packages

**Comment by mmcgahan** [comment]
ah, you're referring to the `releases` page containing tags for the platform - yeah I'll see if I can get the tags pushed there as well

**Comment by mmcgahan** [comment]
tagging is fixed https://github.com/meetup/meetup-web-platform/releases

**Pull request merged**
