### PR TITLE
Use meetup-web-mocks testUtils

### PR DESCRIPTION
**Pull request by sadafie**
remove methods that were moved to meetup-web-mocks and update pkg

Fixes https://meetup.atlassian.net/browse/WP-98

### CODE REVIEW

**Comment by sadafie** [comment]
I'm pretty sure we would consider this a breaking change since `mup-web` would break if the pkg is updated. 

i'm going to make a corresponding update in the `mup-web` repo.

**Comment by mmcgahan** [comment]
Any reason not to move the rest of `testUtils` over to the mocks repo? Sort of a fine line between what is an isn't included, and the stuff that has been left in the platform repo isn't really platform-specific.

**Comment by mmcgahan** [comment]
Breaking changes need a bump in the minor version number in `Makefile`, and an entry in `CHANGELOG` to indicate what a consumer app needs to do to upgrade

**Comment by sadafie** [comment]
> Any reason not to move the rest of testUtils over to the mocks repo? Sort of a fine line between what is an isn't included, and the stuff that has been left in the platform repo isn't really platform-specific.

The rest seemed app server specific utilities that consumer apps wouldn't/don't use? It would also introduce Hapi, Cookie, rxjs, etc. dependencies. If we think it's better to move the whole thing I can, but if it does make sense to keep them separate, maybe it's just a naming conflict/confusion and I can rename one of the files.

**Comment by mmcgahan** [comment]
That makes sense - let's see how it goes with keeping them separate. Definitely don't want to overload the dependencies for something as 'simple' as a mocks lib

**Pull request merged**
