### PR TITLE
Less rxjs in bundle

### PR DESCRIPTION
**Pull request by mattkime**

### CODE REVIEW

**Comment by mmcgahan** [comment]
Looking good so far - I think `src/epics/sync.js` will also need a pass

**Comment by mmcgahan** [comment]
If you run the integration tests without `--silent`, the error appears:

```
Unhandled rejection TypeError: _Observable.Observable.create(...).first is not a function
          at Object.en-US (/Users/mikem/meetup-web-platform/src/renderers/server-render.jsx:189:4)
          at /Users/mikem/meetup-web-platform/src/routes/appRouteHandler.js:15:43
          at Object.<anonymous>.internals.handler (/Users/mikem/meetup-web-platform/node_modules/hapi/lib/handler.js:99:36)
```

**Comment by mattkime** [comment]
master - 966k / 213k gzipped
w/ 806k / 184k gzipped

**Comment by mmcgahan** [comment]
flip, that's excellent

**Comment by mattkime** [comment]
@mmcgahan just want to make sure you noticed mergeMap instead of flatMap. same function.

**Comment by mmcgahan** [comment]
yeah, I've sort of had that name change as a todo in the back of my mind for awhile but never actually did it - thanks. With this update + the dllPlugin ticket, our bundles should be markedly improved

**Pull request merged**
