### PR TITLE
Update react-redux dep

### PR DESCRIPTION
**Pull request by chenrui333**
Update react-redux dependency, also upgrade react to v16.4 (as required for react-redux v6.0.0).

Relates to https://github.com/meetup/pro-web/pull/1309

### CODE REVIEW

**Comment by sadafie** [comment]
you'll need to update the lock file for this.
i'd recommend:
`yarn lerna clean`
`yarn`

There's only a root-level yarn lock file. at the package level there is only package.json files.

**Comment by sadafie** [comment]
what changes does react-redux v6 introduce since it's a major bump? will there need to be code changes either here in the platform code, or in pro-web/mup-web?

**Comment by chenrui333** [comment]
The only big change I saw in the release note is the Context API (introduced by 16.4) which requires our mwp component to bump the compatible version to 16.4

Pro is already using 16.9, so I dont necessarily see the issue.

**Comment by sadafie** [comment]
Looks like there are some breaking changes and behavior changes: https://github.com/reduxjs/react-redux/releases/tag/v6.0.0

Ideally, we'd want to test these platform changes against both mup-web and pro-web. If this causes either app to break, we'd probably want to consider making this upgrade a major version bump here as well. If you need help doing this, happy to pair!

**Comment by chenrui333** [comment]
Sure, we can do it next week, thanks!

**Comment by chenrui333** [comment]
Sure, I am fixing the fail build now.

**Comment by chenrui333** [comment]
Some errors with `yarn flow`:
```
$ /Users/rchen/mup/meetup-web-platform/node_modules/.bin/flow
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/mwp-tracking-plugin/src/activity.js:137:33

Missing type annotation for cookieConfig.

     134│  * Read from request data to prepare/modify response. Mainly looking for new
     135│  * tracking cookies that need to be set using request.response.state.
     136│  */
     137│ export const getOnPreResponse = cookieConfig => (request, h) => {
     138│ 	const { browserIdCookieName, trackIdCookieName, domain } = cookieConfig;
     139│ 	const pluginData = request.plugins[ACTIVITY_PLUGIN_NAME];
     140│ 	const browserId = pluginData[browserIdCookieName];


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/mwp-tracking-plugin/src/activity.js:137:50

Missing type annotation for request.

     134│  * Read from request data to prepare/modify response. Mainly looking for new
     135│  * tracking cookies that need to be set using request.response.state.
     136│  */
     137│ export const getOnPreResponse = cookieConfig => (request, h) => {
     138│ 	const { browserIdCookieName, trackIdCookieName, domain } = cookieConfig;
     139│ 	const pluginData = request.plugins[ACTIVITY_PLUGIN_NAME];
     140│ 	const browserId = pluginData[browserIdCookieName];


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/mwp-tracking-plugin/src/activity.js:137:59

Missing type annotation for h.

     134│  * Read from request data to prepare/modify response. Mainly looking for new
     135│  * tracking cookies that need to be set using request.response.state.
     136│  */
     137│ export const getOnPreResponse = cookieConfig => (request, h) => {
     138│ 	const { browserIdCookieName, trackIdCookieName, domain } = cookieConfig;
     139│ 	const pluginData = request.plugins[ACTIVITY_PLUGIN_NAME];
     140│ 	const browserId = pluginData[browserIdCookieName];
```

**Comment by chenrui333** [comment]
@sadafie Sounds good!

**Comment by mmcgahan** [comment]
bump @chenrui333 - I think you can merge this once you pull master and let yarn resolve the lockfile conflict

**Comment by sadafie** [comment]
This has been sitting open for awhile. Closing.

**Pull request closed without merging**
