### PR TITLE
fix(renderer): bring renderer part back after NewRelic cleanup

### PR DESCRIPTION
**Pull request by ekobtsev**
Brings back part of the renderer which shouldn't be removed in NewRelic removal

Related to this: https://github.com/meetup/meetup-web-platform/pull/670

### CODE REVIEW

**Comment by softprops** [comment]
Oh crap did the new relic removal break page rendering?

**Comment by softprops** [comment]
What was the impact?

**Comment by ekobtsev** [comment]
@softprops I think that change was never deployed

**Comment by chenrui333** [comment]
This might solve the mup-web side issue, which has struggle with local integration testing.

**Comment by chenrui333** [comment]
I currently have a open PR for it.

**Pull request merged**
