### PR TITLE
Adding object.values to polyfill list for IE + Safari

### PR DESCRIPTION
**Pull request by eilinora**

### CODE REVIEW

**Comment by mmcgahan** [comment]
needs a snapshot update.

**Comment by eilinora** [comment]
@mmcgahan I tried running yarn run test and am seeing this
```
$ yarn run test
yarn run v0.27.5
$ yarn run flow && lerna run test --stream
Launching Flow server for /Users/lori/projects/meetup-web-platform
Spawned flow server (pid=18844)
Logs will go to /private/tmp/flow/zSUserszSlorizSprojectszSmeetup-web-platform.log
packages/mwp-core/src/renderers/browser-render.jsx:4
  4: import { getInitialState, getBrowserCreateStore } from 'mwp-store/lib/browser';
                                                            ^^^^^^^^^^^^^^^^^^^^^^^ mwp-store/lib/browser. Required module not found

packages/mwp-core/src/renderers/browser-render.jsx:5
  5: import { getRouteResolver } from 'mwp-router/lib/util';
                                      ^^^^^^^^^^^^^^^^^^^^^ mwp-router/lib/util. Required module not found

packages/mwp-core/src/renderers/browser-render.jsx:6
  6: import BrowserApp from 'mwp-app-render/lib/components/BrowserApp';
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mwp-app-render/lib/components/BrowserApp. Required module not found

packages/mwp-core/src/renderers/server-render.jsx:11
 11: import { API_ROUTE_PATH } from 'mwp-api-proxy-plugin';
                                    ^^^^^^^^^^^^^^^^^^^^^^ mwp-api-proxy-plugin. Required module not found

packages/mwp-core/src/renderers/server-render.jsx:12
 12: import { Forbidden, NotFound, Redirect, SERVER_RENDER } from 'mwp-router';
                                                                  ^^^^^^^^^^^^ mwp-router. Required module not found

packages/mwp-core/src/renderers/server-render.jsx:13
 13: import { getServerCreateStore } from 'mwp-store/lib/server';
                                          ^^^^^^^^^^^^^^^^^^^^^^ mwp-store/lib/server. Required module not found

packages/mwp-core/src/renderers/server-render.jsx:14
 14: import Dom from 'mwp-app-render/lib/components/Dom';
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mwp-app-render/lib/components/Dom. Required module not found

packages/mwp-core/src/renderers/server-render.jsx:15
 15: import ServerApp from 'mwp-app-render/lib/components/ServerApp';
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mwp-app-render/lib/components/ServerApp. Required module not found

packages/mwp-store/src/browser/index.js:3
  3: import getClickWriter from 'mwp-tracking-plugin/lib/util/clickWriter';
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mwp-tracking-plugin/lib/util/clickWriter. Required module not found

packages/mwp-store/src/browser/index.js:4
  4: import { getApiMiddleware } from 'mwp-api-state';
                                      ^^^^^^^^^^^^^^^ mwp-api-state. Required module not found

packages/mwp-store/src/middleware/injectPromise.js:3
  3: import { API_REQ } from 'mwp-api-state';
                             ^^^^^^^^^^^^^^^ mwp-api-state. Required module not found

packages/mwp-store/src/reducer.js:8
  8: import { api, app, API_RESP_COMPLETE } from 'mwp-api-state';
                                                 ^^^^^^^^^^^^^^^ mwp-api-state. Required module not found

packages/mwp-store/src/reducer.js:9
  9: import { routing } from 'mwp-router';
                             ^^^^^^^^^^^^ mwp-router. Required module not found

packages/mwp-store/src/reducer.js:10
 10: import { reducer as clickTracking } from 'mwp-tracking-plugin/lib/util/clickState';
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mwp-tracking-plugin/lib/util/clickState. Required module not found

packages/mwp-sw-plugin/src/index.js:2
  2: const buildPaths = require('mwp-cli/src/config').paths;
                                ^^^^^^^^^^^^^^^^^^^^ mwp-cli/src/config. Required module not found

packages/mwp-tracking-plugin/src/activity.js:22
 22: 	const offset: String = new Date().getTimezoneOffset() * 60000; // gets detected timezone + converts to milliseconds
     	                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ number. This type is incompatible with
 22: 	const offset: String = new Date().getTimezoneOffset() * 60000; // gets detected timezone + converts to milliseconds
     	              ^^^^^^ String

packages/mwp-tracking-plugin/src/activity.js:23
 23: 	const nowUTC: Date = new Date(Date.now() + offset);
     	                                           ^^^^^^ String. This type cannot be added to
 23: 	const nowUTC: Date = new Date(Date.now() + offset);
     	                              ^^^^^^^^^^ number

packages/mwp-tracking-plugin/src/activity.js:27
 27: 	const NY_OFFSET: String = -14400000;
     	                          ^^^^^^^^^ number. This type is incompatible with
 27: 	const NY_OFFSET: String = -14400000;
     	                 ^^^^^^ String

packages/mwp-tracking-plugin/src/activity.js:28
 28: 	const newNow: Date = new Date(nowUTC.getTime() - NY_OFFSET);
     	                                                 ^^^^^^^^^ String. The operand of an arithmetic operation must be a number.

packages/mwp-tracking-plugin/src/util/avro.js:2
  2: const log = require('mwp-logger-plugin').logger;
                         ^^^^^^^^^^^^^^^^^^^ mwp-logger-plugin. Required module not found

```

Is there another command i should be running?

**Comment by mmcgahan** [comment]
flow fixes are pushed - still need snapshot update

**Comment by mmcgahan** [comment]
to update the snapshot, you'll probably need to run something like `yarn test -- -u`

**Pull request merged**
